// <auto-generated />
using System;
using Inventory_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Inventory_API.Migrations
{
    [DbContext(typeof(RestContext))]
    [Migration("20220322143010_ReminderEnum")]
    partial class ReminderEnum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Inventory_API.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorUsername")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUsername");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorUsername")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentItemId")
                        .HasColumnType("int");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUsername");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ParentItemId");

                    b.HasIndex("RoomId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.List", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorUsername")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUsername");

                    b.ToTable("Lists");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.ListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ParentListId");

                    b.ToTable("ListItems");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorUsername")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.Property<string>("RecipientUsername")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUsername");

                    b.HasIndex("RecipientUsername");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReminderTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RepeatFrequency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorUsername")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUsername");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Username1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Username");

                    b.HasIndex("RoomId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("Username1");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.Category", b =>
                {
                    b.HasOne("Inventory_API.Data.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUsername");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.Item", b =>
                {
                    b.HasOne("Inventory_API.Data.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUsername");

                    b.HasOne("Inventory_API.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Inventory_API.Data.Entities.Item", "ParentItem")
                        .WithMany("Items")
                        .HasForeignKey("ParentItemId");

                    b.HasOne("Inventory_API.Data.Entities.Room", "Room")
                        .WithMany("Items")
                        .HasForeignKey("RoomId");

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("ParentItem");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.List", b =>
                {
                    b.HasOne("Inventory_API.Data.Entities.User", "Author")
                        .WithMany("Lists")
                        .HasForeignKey("AuthorUsername");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.ListItem", b =>
                {
                    b.HasOne("Inventory_API.Data.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("Inventory_API.Data.Entities.List", "ParentList")
                        .WithMany("Items")
                        .HasForeignKey("ParentListId");

                    b.Navigation("Item");

                    b.Navigation("ParentList");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.Message", b =>
                {
                    b.HasOne("Inventory_API.Data.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUsername");

                    b.HasOne("Inventory_API.Data.Entities.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientUsername");

                    b.Navigation("Author");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.Reminder", b =>
                {
                    b.HasOne("Inventory_API.Data.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.Room", b =>
                {
                    b.HasOne("Inventory_API.Data.Entities.User", "Author")
                        .WithMany("Rooms")
                        .HasForeignKey("AuthorUsername");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.User", b =>
                {
                    b.HasOne("Inventory_API.Data.Entities.Room", null)
                        .WithMany("SharedWith")
                        .HasForeignKey("RoomId");

                    b.HasOne("Inventory_API.Data.Entities.User", null)
                        .WithMany("Friends")
                        .HasForeignKey("Username1");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.Item", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.List", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.Room", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("SharedWith");
                });

            modelBuilder.Entity("Inventory_API.Data.Entities.User", b =>
                {
                    b.Navigation("Friends");

                    b.Navigation("Lists");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
